DEBUG: True

# 数据库配置,需修改为自己的数据库连接
SQLALCHEMY_DATABASE_URI: "mysql+pymysql://user:password@ip:port/database"
SQLALCHEMY_COMMIT_ON_TEARDOWN: True
SQLALCHEMY_TRACK_MODIFICATIONS: False

# 定时任务配置
SCHEDULER_API_ENABLED: True

# 用于CORS放开的来源
ORIGINS:
  - http://localhost:5173